import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React, { useMemo, useState } from 'react'
import { AiOutlineHome } from 'react-icons/ai';
import { useSelector } from 'react-redux';
import ShoppingCartOutlinedIcon from '@material-ui/icons/ShoppingCartOutlined'

import {
    Banner14,
    Banner15,
    Banner17,
    Banner18,
    Banner19,
    Banner20,
    Banner22,
    Banner23,
    Banner24,
    Banner25,
    Banner26,
    Banner27,
    Banner28,
    Banner29,
    Banner30,
    Banner32,
    Banner33,
    Banner34
} from '../BannerImages/index'
import Banner from '../components/Banner';
import CheckoutProduct from '../components/CheckoutProduct';
import { Footer } from '../components/Footer';
import HeaderItems from '../components/HeaderItems';
import Navbar from '../components/Navbar';
import SubTotal from '../components/Subtotal';
import { getUser } from '../features/authSlice';
import { selectBasketItems } from '../features/basketSlice';

const Checkout = () => {

    const bannerImages = [Banner25, Banner26, Banner27, Banner15, Banner14, Banner17, Banner18, Banner19, Banner20, Banner22, Banner23, Banner24, Banner28, Banner29, Banner30, Banner29, Banner32, Banner33, Banner34]

    const [groupedItemsInBasket, setGroupedItemsInBasket] = useState([])
    const user = useSelector(getUser);
    const basket = useSelector(selectBasketItems);

    useMemo(() => {
        const groupedItems = basket.reduce((results, item) => {
            (results[item.id] = results[item.id] || []).push(item);
            // console.log(results);
            return results;
        }, {});
        setGroupedItemsInBasket(groupedItems)
    }, [basket])

    // console.log(basket);
    return (
        <div className="checkout">
            <Head>
                <title>Checkout</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <HeaderItems />
            <Banner images={bannerImages} />
            <div className="relative top-[18rem] md:top-[20rem] py-8">
                <div className="flex flex-col items-center justify-center ">
                    <div className="flex flex-col text-center md:mt-[6rem] lg:mt-[8rem] py-4">
                        <h3 className="text-xl font-bold">Hello, {user ? user.email : "Guest"}</h3>
                        <h2 className="text-lg font-semibold">
                            {basket.length === 0 ? "No Product added - Empty Cart" : (
                                <div className="flex text-xl items-center justify-center text-center">
                                    <ShoppingCartOutlinedIcon />
                                    <span className="font-semibold text-[#fcba03]">Cart</span>
                                </div>
                            )}
                        </h2>
                        {basket.length === 0 && (<Image src="https://m.media-amazon.com/images/G/31/cart/empty/kettle-desaturated._CB424694257_.svg" height="400" width="400" className="mt-10" />)}
                    </div>
                    <div className="flex flex-col py-8 mt-8">
                        {Object.entries(groupedItemsInBasket).map(([key, items]) => (

                            < CheckoutProduct
                                key={key}
                                id={items[0].id}
                                title={items[0].title}
                                image={items[0].image}
                                price={items[0].price}
                                rating={items[0].rating}
                                details={items[0].detail}
                                quantity={items.length}
                            />

                        ))}
                    </div>
                    {basket.length === 0 && <Link href='/' className="authButton w-[15rem] text-xl font-semibold mb-16">Go To Home <span className="ml-2 my-auto"><AiOutlineHome /></span></Link>}
                </div>
            </div>
            <div className="">
                <SubTotal />
            </div>
            <div className="relative bottom-0 mt-60">
                <Footer />
            </div>

        </div>
    )
}

export default Checkout