import Head from 'next/head';
import React, { useEffect, useState } from 'react'
import { Footer } from '../components/Footer';
import HeaderItems from '../components/HeaderItems';
import ItemSets from '../components/ItemSets';
import Navbar from '../components/Navbar';
import { db } from '../Firebase';
import { CAd1, CAd2, CAd3, CAd4 } from '../BannerImages'
import Ads from '../components/Ads';

const Computers = () => {
  const [productData, setProductData] = useState([])
  const Images = [CAd1, CAd2, CAd3, CAd4]
  useEffect(() => {
    db.collection("LaptopData").onSnapshot((snapshot) => {
      // eslint-disable-next-line array-callback-return
      snapshot.docs.map((doc) => {
        var data = doc.data()
        setProductData(product => [...product, data])

      });
    });
  }, []);

  return (
    <div>
      <Head>
        <title>Laptops</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeaderItems />

      <Ads images={Images} />

      <div className="relative top-[18rem] md:top-[28rem] py-8">
        <ItemSets productData={productData} image="https://m.media-amazon.com/images/G/31/img22/laptops/hp1415/1500x300._CB632654343_.jpg" />
        <Footer />
      </div>

    </div>
  )
}

export default Computers