import Head from 'next/head';
import Image from 'next/image';
import React, { useEffect, useState } from 'react'
import { Footer } from '../components/Footer';
import HeaderItems from '../components/HeaderItems';
import ItemSets from '../components/ItemSets';
import Navbar from '../components/Navbar';
import { db } from '../Firebase';
import { EAd, EAd1, EAd2, EAd3 } from '../BannerImages'
import Ads from '../components/Ads';

const Electronics = () => {
    const [productData, setProductData] = useState([])
    const Images = [EAd, EAd1, EAd2, EAd3]

    useEffect(() => {
        db.collection("ElectronicsData").onSnapshot((snapshot) => {
            // eslint-disable-next-line array-callback-return
            snapshot.docs.map((doc) => {
                var data = doc.data()
                setProductData(product => [...product, data])

            });
        });
    }, []);

    return (
        <div>
            <Head>
                <title>Electronics</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <HeaderItems />

            <Ads images={Images} />

            <div className="relative top-[18rem] md:top-[28rem] py-8">

                <ItemSets productData={productData} />
                <Footer />
            </div>

        </div>
    )
}

export default Electronics