import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import {
  Banner14, Banner15, Banner16, Banner17, Banner18, Banner19, Banner20, Banner21, Banner22, Banner23, Banner24, Banner25, Banner26, Banner27, Banner28, Banner29, Banner30, Banner31, Banner32, Banner33, Banner34, Banner35, Banner36, Banner37, Banner38, Banner39, Banner40
} from '../BannerImages/index'
import Banner from '../components/Banner'
import { db } from '../Firebase'
import ItemSets from '../components/ItemSets'
import Navbar from '../components/Navbar'
import HeaderItems from '../components/HeaderItems'
import { Footer } from '../components/Footer'

export default function Home() {

  const [productData, setProductData] = useState([])

  const bannerImages = [Banner25, Banner15, Banner14, Banner16, Banner17, Banner18, Banner19, Banner20, Banner21, Banner22, Banner23, Banner24, Banner26, Banner27, Banner28, Banner29, Banner30, Banner31, Banner32, Banner33, Banner34, Banner35, Banner36, Banner37, Banner38, Banner39, Banner40]

  useEffect(() => {
    db.collection("HomeProductsData").onSnapshot((snapshot) => {
      // eslint-disable-next-line array-callback-return
      snapshot.docs.map((doc) => {
        var data = doc.data()
        setProductData(product => [...product, data])

      });
    });
  }, []);

  console.log(productData);

  return (
    <div className="relative">
      <Head>
        <title>amazon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeaderItems />
      <Banner images={bannerImages} />

      <div className="homeScreen relative top-[18rem] md:top-[28rem] py-8">
        <ItemSets productData={productData} />
        <Footer />
      </div>
      <script async="false" type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCBWMBOoCUL3dxkoQueuZx5GjyKEd1hKFY&libraries=places"></script>
    </div>
  )
}

