import Head from 'next/head'
import React from 'react'
import Checkout from '../components/Checkout'
import { Footer } from '../components/Footer'
import HeaderItems from '../components/HeaderItems'
import Navbar from '../components/Navbar'

const Payment = () => {
    return (
        <div>
            <Head>
                <title>Payment</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <HeaderItems />
            <div className="relative top-[7rem] py-8">
                <Checkout />
                <Footer />
            </div>

        </div>
    )
}
export default Payment