import Head from 'next/head';
import React from 'react'
import { useSelector } from 'react-redux';
import HeaderItems from '../components/HeaderItems';
import Navbar from '../components/Navbar';
import Deals from '../components/prime/Banners/Deals';
import Delivery from '../components/prime/Banners/Delivery';
import Gaming from '../components/prime/Banners/Gaming';
import Reward from '../components/prime/Banners/Reward';
import GetStarted from '../components/prime/Banners/GetStarted';
import PrimeSlider from '../components/prime/PrimeSlider/PrimeSlider';
import { getUser } from '../features/authSlice';
import Reading from '../components/prime/Entertainment/Reading';
import Songs from '../components/prime/Entertainment/Songs';
import Movies from '../components/prime/Entertainment/Movies';

const Prime = () => {
    const user = useSelector(getUser);
    return (
        <>
            <Head>
                <title>Prime</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <HeaderItems />
            <div className="relative top-[2rem] py-8">
                <div className="first_hiddenContainer" />
                <div className="firstContainer">
                    <div className="flex flex-col gap-[0.5rem] max-w-full md:p-[5rem] pt-4 pb-[7.5rem] text-black items-center text-center">
                        <div className="flex flex-col gap-4">
                            <span className="md:mt-[7.5] font-medium text-[1.5rem] md:text-[2.2rem]">Welcome {user ? user.displayName || user.email : "Guest"}</span>
                            <div className="flex flex-col">
                                <span className="text-[1rem] md:text-[1.25rem] font-medium">One simple membership, many benefits.</span>
                                <span className="text-[1rem] md:text-[1.25rem] font-medium">Check out what is included below.</span>
                                <span className="text-[1rem] md:text-[1.25rem] font-medium">The best of shopping and entertainment is all yours.</span>
                            </div>
                        </div>
                        <div className="flex flex-col gap-[0.5rem] max-w-[25rem] items-center">
                            <span className="mt-[20px] text-[0.8rem] md:text-[1rem] cursor-pointer p-[1.2rem] border rounded-lg text-black outline-none bg-[#fcba03] font-bold max-w-[16rem] hover:bg-[#e47f0c]">JOIN PRIME AT ₹179 PER MONTH</span>
                            <p className="text-black font-medium">Eligible with select credit cards or debit cards</p>
                            <span className="mt-[20px] text-[0.8rem] md:text-[1rem] cursor-pointer p-[1.2rem] border rounded-lg text-black outline-none bg-[#fcba03] font-bold max-w-[16rem] hover:bg-[#e47f0c]">JOIN PRIME AT ₹1,499 PER YEAR</span>
                            <p className="text-black font-medium">With any credit/debit card, net banking or other electronic payment methods.</p>
                        </div>
                    </div>
                </div>
            </div>
            <PrimeSlider />

            <div className="max-w-[90%] flex flex-col m-auto gap-[2.5rem] mt-[2.5rem]">
                <span

                    className="capitalize text-[2rem] text-center font-semibold mb-20"

                >Get the best of shopping and entertainment with Prime</span>
                <Movies />
                <Deals />
                <Songs />
                <Gaming />
                <Reward />
                <Reading />
                <Delivery />
                <GetStarted />
            </div>
        </>
    )
}

export default Prime