import Head from 'next/head'
import React from 'react'
import { Footer } from '../components/Footer'
import HeaderItems from '../components/HeaderItems'
import Navbar from '../components/Navbar'
import Success from '../components/Success'

const Success = () => {
    return (
        <div>
            <Head>
                <title>Order Confirmed</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <HeaderItems />
            <div className="relative top-[2rem] py-8">
                <Success />
                <Footer />
            </div>

        </div>
    )
}

export default Success