import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react'
import CurrentProduct from '../../../components/CurrentProduct';
import HeaderItems from '../../../components/HeaderItems';
import Navbar from '../../../components/Navbar';
import { db } from '../../../Firebase';

const Product = () => {
    const router = useRouter();
    const { id, type } = router.query
    const [productData, setProductData] = useState([])

    // console.log(type);

    useEffect(() => {
        db.collection(`${type}Data`).onSnapshot((snapshot) => {
            // eslint-disable-next-line array-callback-return
            snapshot.docs.map((doc) => {
                var data = doc.data()
                setProductData(product => [...product, data])

            });
        });
        // eslint-disable-next-line
    }, []);

    return (
        <div>
            <Head>
                <title>Single Product</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            <div className="relative top-[1rem] pt-1">

                {productData?.map((product) => (
                    (product.id === id) && <CurrentProduct SingleProduct={product} />
                ))}

            </div>
        </div>
    )
}

export default Product